var userInfo =

{
  "login": "LindsayEisberg",
  "id": 8022632,
  "avatar_url": "https://avatars.githubusercontent.com/u/8022632?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/LindsayEisberg",
  "html_url": "https://github.com/LindsayEisberg",
  "followers_url": "https://api.github.com/users/LindsayEisberg/followers",
  "following_url": "https://api.github.com/users/LindsayEisberg/following{/other_user}",
  "gists_url": "https://api.github.com/users/LindsayEisberg/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/LindsayEisberg/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/LindsayEisberg/subscriptions",
  "organizations_url": "https://api.github.com/users/LindsayEisberg/orgs",
  "repos_url": "https://api.github.com/users/LindsayEisberg/repos",
  "events_url": "https://api.github.com/users/LindsayEisberg/events{/privacy}",
  "received_events_url": "https://api.github.com/users/LindsayEisberg/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Lindsay Eisberg",
  "company": "",
  "blog": "",
  "location": "United States",
  "email": "lindsay.eisberg@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 7,
  "following": 13,
  "created_at": "2014-06-30T04:35:41Z",
  "updated_at": "2015-01-28T03:35:38Z"
};
